In [2]:
import pandas as pd

In [6]:
data = pd.read_csv("../data/results.csv")
data[(data["home_team"] == "Spain") | (data["away_team"] == "Spain")]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
618,1920-08-28,Spain,Denmark,1,0,Olympic Games,Brussels,Belgium,True
622,1920-08-29,Belgium,Spain,3,1,Olympic Games,Antwerp,Belgium,False
629,1920-09-01,Spain,Sweden,2,1,Olympic Games,Antwerp,Belgium,True
631,1920-09-02,Spain,Italy,2,0,Olympic Games,Antwerp,Belgium,True
633,1920-09-05,Spain,Netherlands,3,1,Olympic Games,Antwerp,Belgium,True
...,...,...,...,...,...,...,...,...,...
48800,2025-10-14,Spain,Bulgaria,4,0,FIFA World Cup qualification,Valladolid,Spain,False
48877,2025-11-15,Georgia,Spain,0,4,FIFA World Cup qualification,Tbilisi,Georgia,False
48921,2025-11-18,Spain,Turkey,2,2,FIFA World Cup qualification,Seville,Spain,False
49131,2026-03-27,Spain,Serbia,3,0,Friendly,Villarreal,Spain,False
49172,2026-03-31,Spain,Egypt,0,0,Friendly,Barcelona,Spain,False

In [7]:
data = pd.read_csv("../data/results.csv")
data[(data["home_team"] == "Argentina") | (data["away_team"] == "Argentina")]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
145,1902-07-20,Uruguay,Argentina,0,6,Friendly,Montevideo,Uruguay,False
155,1903-09-13,Argentina,Uruguay,2,3,Friendly,Buenos Aires,Argentina,False
180,1905-08-15,Argentina,Uruguay,0,0,Copa Lipton,Buenos Aires,Argentina,False
193,1906-08-15,Uruguay,Argentina,0,2,Copa Lipton,Montevideo,Uruguay,False
195,1906-10-21,Argentina,Uruguay,2,1,Copa Newton,Buenos Aires,Argentina,False
...,...,...,...,...,...,...,...,...,...
48706,2025-10-10,Argentina,Venezuela,1,0,Friendly,Miami Gardens,United States,True
48799,2025-10-14,Puerto Rico,Argentina,0,6,Friendly,Fort Lauderdale,United States,True
48868,2025-11-14,Angola,Argentina,0,2,Friendly,Luanda,Angola,False
49117,2026-03-27,Argentina,Mauritania,2,1,Friendly,Buenos Aires,Argentina,False
49195,2026-03-31,Argentina,Zambia,5,0,Friendly,Buenos Aires,Argentina,False

In [8]:
data = pd.read_csv("../data/results.csv")
data[(data["home_team"] == "Brazil") | (data["away_team"] == "Brazil")]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
448,1914-09-20,Argentina,Brazil,3,0,Friendly,Buenos Aires,Argentina,False
449,1914-09-27,Argentina,Brazil,0,1,Copa Roca,Buenos Aires,Argentina,False
481,1916-07-08,Brazil,Chile,1,1,Copa América,Buenos Aires,Argentina,True
482,1916-07-10,Argentina,Brazil,1,1,Copa América,Buenos Aires,Argentina,False
484,1916-07-12,Brazil,Uruguay,1,2,Copa América,Buenos Aires,Argentina,True
...,...,...,...,...,...,...,...,...,...
48793,2025-10-14,Japan,Brazil,3,2,Kirin Cup,Tokyo,Japan,False
48890,2025-11-15,Brazil,Senegal,2,0,Friendly,London,England,True
48963,2025-11-18,Brazil,Tunisia,1,1,Friendly,Lille,France,True
49092,2026-03-26,Brazil,France,1,2,Friendly,Foxborough,United States,True
49198,2026-03-31,Brazil,Croatia,3,1,Friendly,Orlando,United States,True